### ISSUE TITLE
Ubuntu 14.04.1 LTS not building 

### ISSUE THREAD

**Issue by iShift** [PrivacySolutions/i2pd#137]
> ~$ git clone https://github.com/PrivacySolutions/i2pd.git
Cloning into 'i2pd'...
remote: Counting objects: 5862, done.
remote: Compressing objects: 100% (117/117), done.
Receiving objects: 100% (5862/5862), 2.10 MiB | 1.23 MiB/s, done.
remote: Total 5862 (delta 59), reused 1 (delta 0)
Resolving deltas: 100% (4079/4079), done.
Checking connectivity... done.
> ~$ cd i2pd/
> ~/i2pd$ make
test -d obj || mkdir obj
g++ -g -Wall -fPIC -std=c++11   -c -o obj/AddressBook.o AddressBook.cpp
AddressBook.cpp:10:28: fatal error: cryptopp/osrng.h: No such file or directory
 #include <cryptopp/osrng.h>
                            ^
compilation terminated.
make: *** [obj/AddressBook.o] Error 1
___

uname -a
Linux cjdns.ru 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by orignal** [comment]
А crypto++ установить если?

**Comment by kytvi2p** [comment]
The following dev packages are needed to build

`libboost-dev llibboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libcrypto++-dev libboost-date-time-dev`

**Comment by kytvi2p** [comment]
Proof:

    # dpkg -S osrng.h
    libcrypto++-dev: /usr/include/crypto++/osrng.h

Install libcrypto++-dev (and the other deps) and it'll work.

If compiling it proves to be too difficult you can install with a package from https://launchpad.net/~i2p-maintainers/+archive/ubuntu/i2p

**Comment by iShift** [comment]
ok, https://github.com/PrivacySolutions/i2pd/pull/139
