### ISSUE TITLE
Addressbook subscriptions ?

### ISSUE THREAD

**Issue by iShift** [PrivacySolutions/i2pd#142]
How i see 0.6.0 version support Addressbook, where can i find docs hot to configure it?
https://github.com/PrivacySolutions/i2pd/releases/tag/0.6.0

**Comment by orignal** [comment]
Положить subscriptions.txt в ~/.i2pd
Точно такой же как джаве

**Comment by iShift** [comment]
Ок, надо документацию писать... 

Тогда еще тут спрошу заодно - Собрал, запустил на Ubuntu, сайты не открывает, даже флибусту 

Картина такая Routers: 150 Floodfills: 75 LeaseSets: 0 

Почему LeaseSets: 0  - непонятно, порты открыл

**Comment by orignal** [comment]
LeaseSets: 0  потому что не floodfill.
Тут только полученные извне видны.
Которые по запросу внтури своего destination  сидят.

**Comment by iShift** [comment]
Спасибо!
